#!/usr/bin/env python3
"""
Plugin Health Check Script
Generated by plugin-health-agent

Performs comprehensive health analysis using 5-factor weighted scoring:
- Structure validity (25%)
- Syntax correctness (20%)
- MCP connectivity (15%)
- Component loading (25%)
- Stability metrics (15%)
"""

import os
import sys
import json
import yaml
from pathlib import Path
from typing import Dict, List, Tuple, Optional
from dataclasses import dataclass, field
from datetime import datetime

@dataclass
class HealthScore:
    """Represents plugin health scores"""
    structure: float = 0.0
    syntax: float = 0.0
    mcp: float = 0.0
    loading: float = 0.0
    stability: float = 0.0

    @property
    def total(self) -> float:
        """Calculate weighted total score"""
        weights = {
            'structure': 0.25,
            'syntax': 0.20,
            'mcp': 0.15,
            'loading': 0.25,
            'stability': 0.15
        }
        return (
            self.structure * weights['structure'] +
            self.syntax * weights['syntax'] +
            self.mcp * weights['mcp'] +
            self.loading * weights['loading'] +
            self.stability * weights['stability']
        )

    @property
    def status(self) -> str:
        """Get health status based on score"""
        score = self.total
        if score >= 85:
            return "HEALTHY"
        elif score >= 70:
            return "WARNING"
        elif score >= 50:
            return "CRITICAL"
        else:
            return "FAILING"

@dataclass
class HealthIssue:
    """Represents a detected health issue"""
    error_code: str
    severity: str  # LOW, MEDIUM, HIGH
    component: str
    message: str
    file_path: Optional[str] = None
    auto_fixable: bool = False

def check_structure(plugin_path: Path) -> Tuple[float, List[HealthIssue]]:
    """Check plugin structure validity (25% weight)"""
    issues = []
    score = 100.0

    # Required directories
    required_dirs = ['.claude-plugin', 'agents', 'skills', 'commands', 'hooks']
    for dir_name in required_dirs:
        dir_path = plugin_path / dir_name
        if not dir_path.is_dir():
            issues.append(HealthIssue(
                error_code="E001" if dir_name == '.claude-plugin' else f"E00{required_dirs.index(dir_name)+1}",
                severity="HIGH" if dir_name == '.claude-plugin' else "MEDIUM",
                component="structure",
                message=f"Missing required directory: {dir_name}/",
                auto_fixable=True
            ))
            score -= 20

    # Required files
    plugin_json = plugin_path / '.claude-plugin' / 'plugin.json'
    if plugin_json.exists():
        try:
            with open(plugin_json) as f:
                json.load(f)
        except json.JSONDecodeError:
            issues.append(HealthIssue(
                error_code="E003",
                severity="HIGH",
                component="structure",
                message="Invalid JSON in plugin.json",
                file_path=str(plugin_json),
                auto_fixable=False
            ))
            score -= 25
    else:
        issues.append(HealthIssue(
            error_code="E002",
            severity="HIGH",
            component="structure",
            message="Missing plugin.json",
            auto_fixable=True
        ))
        score -= 25

    return max(0, score), issues

def check_syntax(plugin_path: Path) -> Tuple[float, List[HealthIssue]]:
    """Check syntax correctness (20% weight)"""
    issues = []
    score = 100.0

    # Check agent markdown files
    agents_dir = plugin_path / 'agents'
    if agents_dir.exists():
        for md_file in agents_dir.glob('*.md'):
            content = md_file.read_text()

            # Check for malformed frontmatter (E102)
            if content.startswith('>---'):
                issues.append(HealthIssue(
                    error_code="E102",
                    severity="LOW",
                    component="syntax",
                    message="Malformed YAML frontmatter (starts with >---)",
                    file_path=str(md_file),
                    auto_fixable=True
                ))
                score -= 10
            elif not content.startswith('---'):
                issues.append(HealthIssue(
                    error_code="E101",
                    severity="LOW",
                    component="syntax",
                    message="Missing YAML frontmatter",
                    file_path=str(md_file),
                    auto_fixable=True
                ))
                score -= 10

    # Check skill markdown files
    skills_dir = plugin_path / 'skills'
    if skills_dir.exists():
        for skill_path in skills_dir.iterdir():
            if skill_path.is_dir():
                skill_md = skill_path / 'SKILL.md'
                if skill_md.exists():
                    content = skill_md.read_text()
                    if content.startswith('>---'):
                        issues.append(HealthIssue(
                            error_code="E102",
                            severity="LOW",
                            component="syntax",
                            message="Malformed YAML frontmatter",
                            file_path=str(skill_md),
                            auto_fixable=True
                        ))
                        score -= 5

    return max(0, score), issues

def check_mcp(plugin_path: Path) -> Tuple[float, List[HealthIssue]]:
    """Check MCP configuration (15% weight)"""
    issues = []
    score = 100.0

    # Check for shell expansions in JSON files
    shell_patterns = ['$HOME', '$USER', '~/', '$(', '${', '`']

    for json_file in plugin_path.rglob('*.json'):
        try:
            content = json_file.read_text()
            for pattern in shell_patterns:
                if pattern in content:
                    issues.append(HealthIssue(
                        error_code="E201",
                        severity="HIGH",
                        component="mcp",
                        message=f"Shell expansion detected: {pattern}",
                        file_path=str(json_file),
                        auto_fixable=False  # Needs user input
                    ))
                    score -= 15
                    break
        except Exception:
            pass

    return max(0, score), issues

def check_loading(plugin_path: Path) -> Tuple[float, List[HealthIssue]]:
    """Check component loading (25% weight)"""
    issues = []
    score = 100.0

    # Count agents
    agents_dir = plugin_path / 'agents'
    if agents_dir.exists():
        agent_count = len(list(agents_dir.glob('*.md')))
        if agent_count == 0:
            issues.append(HealthIssue(
                error_code="E503",
                severity="MEDIUM",
                component="loading",
                message="No agents found",
                auto_fixable=False
            ))
            score -= 25

    # Count skills with valid SKILL.md
    skills_dir = plugin_path / 'skills'
    if skills_dir.exists():
        valid_skills = 0
        for skill_path in skills_dir.iterdir():
            if skill_path.is_dir():
                skill_md = skill_path / 'SKILL.md'
                if skill_md.exists() and skill_md.stat().st_size >= 200:
                    valid_skills += 1

        if valid_skills == 0:
            issues.append(HealthIssue(
                error_code="E701",
                severity="MEDIUM",
                component="loading",
                message="No valid skills found",
                auto_fixable=True
            ))
            score -= 25

    return max(0, score), issues

def check_stability(plugin_path: Path) -> Tuple[float, List[HealthIssue]]:
    """Check stability metrics (15% weight)"""
    # Stability is calculated from error history
    # For now, assume stable if structure is intact
    issues = []
    score = 100.0

    # Check for common stability issues
    # (In production, this would check error logs)

    return score, issues

def run_health_check(plugin_path: str) -> Dict:
    """Run comprehensive health check"""
    path = Path(plugin_path)

    if not path.exists():
        return {"error": "Plugin path not found"}

    all_issues: List[HealthIssue] = []
    scores = HealthScore()

    # Run all checks
    scores.structure, structure_issues = check_structure(path)
    all_issues.extend(structure_issues)

    scores.syntax, syntax_issues = check_syntax(path)
    all_issues.extend(syntax_issues)

    scores.mcp, mcp_issues = check_mcp(path)
    all_issues.extend(mcp_issues)

    scores.loading, loading_issues = check_loading(path)
    all_issues.extend(loading_issues)

    scores.stability, stability_issues = check_stability(path)
    all_issues.extend(stability_issues)

    return {
        "plugin": path.name,
        "timestamp": datetime.now().isoformat(),
        "health_score": round(scores.total, 1),
        "status": scores.status,
        "component_scores": {
            "structure": scores.structure,
            "syntax": scores.syntax,
            "mcp": scores.mcp,
            "loading": scores.loading,
            "stability": scores.stability
        },
        "issues": [
            {
                "code": i.error_code,
                "severity": i.severity,
                "component": i.component,
                "message": i.message,
                "file": i.file_path,
                "auto_fixable": i.auto_fixable
            }
            for i in all_issues
        ],
        "issues_count": len(all_issues),
        "auto_fixable_count": sum(1 for i in all_issues if i.auto_fixable)
    }

def main():
    if len(sys.argv) < 2:
        print("Usage: python health-check.py <plugin_path>")
        sys.exit(1)

    result = run_health_check(sys.argv[1])

    if "error" in result:
        print(f"Error: {result['error']}")
        sys.exit(1)

    # Print report
    print("=" * 60)
    print(f"PLUGIN HEALTH REPORT: {result['plugin']}")
    print("=" * 60)
    print(f"\nOverall Score: {result['health_score']}/100 [{result['status']}]")
    print(f"\nComponent Scores:")
    for comp, score in result['component_scores'].items():
        status = "[OK]" if score >= 85 else "[WARN]" if score >= 70 else "[FAIL]"
        print(f"  {comp.capitalize():12} {score:5.1f}/100 {status}")

    if result['issues']:
        print(f"\nIssues Found: {result['issues_count']}")
        for issue in result['issues']:
            print(f"\n  [{issue['code']}] {issue['message']}")
            if issue['file']:
                print(f"    File: {issue['file']}")
            print(f"    Severity: {issue['severity']}")
            print(f"    Auto-fixable: {'Yes' if issue['auto_fixable'] else 'No'}")
    else:
        print("\nNo issues detected!")

    print("\n" + "=" * 60)

    # Exit with appropriate code
    sys.exit(0 if result['status'] == 'HEALTHY' else 1)

if __name__ == "__main__":
    main()
