#!/usr/bin/env python3
"""
Plugin Troubleshooter - Diagnosis Script
Generated by plugin-health-agent

Maps symptoms to error codes and provides root cause analysis.
"""

import os
import sys
import re
import json
from pathlib import Path
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass

@dataclass
class Diagnosis:
    """Represents a diagnosis result"""
    error_code: str
    severity: str
    location: str
    issue: str
    root_cause: str
    fix_suggestion: str
    auto_fixable: bool

# Symptom to error code mapping
SYMPTOM_MAP = {
    "agent not loading": ["E101", "E102", "E103", "E002"],
    "skill not found": ["E701", "E005", "E502"],
    "plugin not recognized": ["E001", "E002", "E003"],
    "yaml error": ["E102", "E103", "E104"],
    "json error": ["E003", "E105"],
    "mcp error": ["E201", "E202", "E203"],
    "permission denied": ["E008", "E205"],
    "golden format": ["E701", "E702", "E703", "E704"],
    "subdirectory": ["E401", "E702", "E703", "E704"],
}

def detect_e102(plugin_path: Path) -> List[Diagnosis]:
    """Detect malformed YAML frontmatter"""
    diagnoses = []

    # Check agents
    agents_dir = plugin_path / "agents"
    if agents_dir.exists():
        for md_file in agents_dir.glob("*.md"):
            content = md_file.read_text()
            if content.startswith(">---"):
                diagnoses.append(Diagnosis(
                    error_code="E102",
                    severity="LOW",
                    location=str(md_file),
                    issue="YAML frontmatter starts with '>---' instead of '---'",
                    root_cause="File was created with incorrect frontmatter delimiter",
                    fix_suggestion="Replace '>---' with '---' at line 1",
                    auto_fixable=True
                ))

    # Check skills
    skills_dir = plugin_path / "skills"
    if skills_dir.exists():
        for skill_path in skills_dir.iterdir():
            if skill_path.is_dir():
                skill_md = skill_path / "SKILL.md"
                if skill_md.exists():
                    content = skill_md.read_text()
                    if content.startswith(">---"):
                        diagnoses.append(Diagnosis(
                            error_code="E102",
                            severity="LOW",
                            location=str(skill_md),
                            issue="YAML frontmatter starts with '>---'",
                            root_cause="Incorrect frontmatter delimiter",
                            fix_suggestion="Replace '>---' with '---' at line 1",
                            auto_fixable=True
                        ))

    return diagnoses

def detect_e201(plugin_path: Path) -> List[Diagnosis]:
    """Detect shell expansions in JSON files"""
    diagnoses = []
    shell_patterns = [
        (r'\$HOME', "$HOME variable"),
        (r'\$USER', "$USER variable"),
        (r'~/', "Tilde expansion"),
        (r'\$\(', "Command substitution"),
        (r'\$\{', "Variable expansion"),
        (r'`', "Backtick command"),
    ]

    for json_file in plugin_path.rglob("*.json"):
        try:
            content = json_file.read_text()
            for pattern, description in shell_patterns:
                if re.search(pattern, content):
                    diagnoses.append(Diagnosis(
                        error_code="E201",
                        severity="HIGH",
                        location=str(json_file),
                        issue=f"Shell expansion detected: {description}",
                        root_cause="MCP cannot process shell expansions at runtime",
                        fix_suggestion="Replace with absolute path",
                        auto_fixable=False
                    ))
                    break
        except Exception:
            pass

    return diagnoses

def detect_e303(plugin_path: Path) -> List[Diagnosis]:
    """Detect name collision between plugin and marketplace"""
    diagnoses = []

    plugin_json = plugin_path / ".claude-plugin" / "plugin.json"
    marketplace_json = plugin_path / ".claude-plugin" / "marketplace.json"

    if plugin_json.exists() and marketplace_json.exists():
        try:
            plugin_data = json.loads(plugin_json.read_text())
            marketplace_data = json.loads(marketplace_json.read_text())

            plugin_name = plugin_data.get("name", "")
            marketplace_name = marketplace_data.get("name", "")

            if plugin_name and plugin_name == marketplace_name:
                diagnoses.append(Diagnosis(
                    error_code="E303",
                    severity="LOW",
                    location=str(marketplace_json),
                    issue=f"Name collision: plugin and marketplace both named '{plugin_name}'",
                    root_cause="Marketplace name should be unique from plugin name",
                    fix_suggestion=f"Rename marketplace to '{plugin_name}-marketplace'",
                    auto_fixable=True
                ))
        except json.JSONDecodeError:
            pass

    return diagnoses

def detect_e401(plugin_path: Path) -> List[Diagnosis]:
    """Detect skill subdirectory violations"""
    diagnoses = []

    skills_dir = plugin_path / "skills"
    if not skills_dir.exists():
        return diagnoses

    for skill_path in skills_dir.iterdir():
        if not skill_path.is_dir():
            continue

        for subdir_name in ["assets", "scripts", "references"]:
            subdir = skill_path / subdir_name
            if not subdir.exists():
                diagnoses.append(Diagnosis(
                    error_code="E401",
                    severity="MEDIUM",
                    location=str(subdir),
                    issue=f"Missing {subdir_name}/ directory",
                    root_cause="Golden Format requires all three subdirectories",
                    fix_suggestion=f"Create {subdir_name}/ with real content",
                    auto_fixable=True
                ))
                continue

            # Check for placeholder only
            files = list(subdir.iterdir())
            real_files = [f for f in files if f.name != ".gitkeep" and f.stat().st_size > 100]

            if len(real_files) == 0:
                diagnoses.append(Diagnosis(
                    error_code="E401",
                    severity="MEDIUM",
                    location=str(subdir),
                    issue=f"{subdir_name}/ contains only placeholders",
                    root_cause="Directory has no real content files",
                    fix_suggestion="Add category-appropriate content files",
                    auto_fixable=True
                ))

    return diagnoses

def detect_e701_to_e704(plugin_path: Path) -> List[Diagnosis]:
    """Detect Golden Format violations"""
    diagnoses = []

    skills_dir = plugin_path / "skills"
    if not skills_dir.exists():
        return diagnoses

    for skill_path in skills_dir.iterdir():
        if not skill_path.is_dir():
            continue

        skill_name = skill_path.name

        # E701: SKILL.md
        skill_md = skill_path / "SKILL.md"
        if not skill_md.exists():
            diagnoses.append(Diagnosis(
                error_code="E701",
                severity="LOW",
                location=str(skill_md),
                issue=f"Missing SKILL.md in {skill_name}",
                root_cause="Golden Format requires SKILL.md in each skill",
                fix_suggestion="Generate SKILL.md with proper frontmatter",
                auto_fixable=True
            ))
        elif skill_md.stat().st_size < 200:
            diagnoses.append(Diagnosis(
                error_code="E701",
                severity="LOW",
                location=str(skill_md),
                issue=f"SKILL.md too small ({skill_md.stat().st_size} bytes)",
                root_cause="SKILL.md should be comprehensive (>200 bytes)",
                fix_suggestion="Expand SKILL.md with full documentation",
                auto_fixable=True
            ))

    return diagnoses

def run_diagnosis(plugin_path: str, symptom: Optional[str] = None) -> Dict:
    """Run full diagnosis on plugin"""
    path = Path(plugin_path)

    if not path.exists():
        return {"error": "Plugin path not found"}

    all_diagnoses: List[Diagnosis] = []

    # Run all detectors
    all_diagnoses.extend(detect_e102(path))
    all_diagnoses.extend(detect_e201(path))
    all_diagnoses.extend(detect_e303(path))
    all_diagnoses.extend(detect_e401(path))
    all_diagnoses.extend(detect_e701_to_e704(path))

    # Filter by symptom if provided
    if symptom:
        symptom_lower = symptom.lower()
        relevant_codes = []
        for key, codes in SYMPTOM_MAP.items():
            if key in symptom_lower:
                relevant_codes.extend(codes)

        if relevant_codes:
            all_diagnoses = [d for d in all_diagnoses if d.error_code in relevant_codes]

    return {
        "plugin": path.name,
        "diagnoses": [
            {
                "error_code": d.error_code,
                "severity": d.severity,
                "location": d.location,
                "issue": d.issue,
                "root_cause": d.root_cause,
                "fix_suggestion": d.fix_suggestion,
                "auto_fixable": d.auto_fixable
            }
            for d in all_diagnoses
        ],
        "total_issues": len(all_diagnoses),
        "auto_fixable": sum(1 for d in all_diagnoses if d.auto_fixable)
    }

def main():
    if len(sys.argv) < 2:
        print("Usage: python diagnose.py <plugin_path> [symptom]")
        sys.exit(1)

    plugin_path = sys.argv[1]
    symptom = sys.argv[2] if len(sys.argv) > 2 else None

    result = run_diagnosis(plugin_path, symptom)

    if "error" in result:
        print(f"Error: {result['error']}")
        sys.exit(1)

    print("=" * 60)
    print(f"DIAGNOSIS REPORT: {result['plugin']}")
    print("=" * 60)

    if symptom:
        print(f"\nSymptom: \"{symptom}\"")

    print(f"\nIssues Found: {result['total_issues']}")
    print(f"Auto-fixable: {result['auto_fixable']}")

    if result['diagnoses']:
        print("\n" + "-" * 60)
        for d in result['diagnoses']:
            print(f"\n[{d['error_code']}] {d['issue']}")
            print(f"  Location: {d['location']}")
            print(f"  Severity: {d['severity']}")
            print(f"  Root Cause: {d['root_cause']}")
            print(f"  Fix: {d['fix_suggestion']}")
            print(f"  Auto-fixable: {'Yes' if d['auto_fixable'] else 'No'}")
    else:
        print("\nNo issues detected!")

    print("\n" + "=" * 60)

    sys.exit(0 if result['total_issues'] == 0 else 1)

if __name__ == "__main__":
    main()
